[build]
  # Directorio donde se ejecuta el build
  base = "."
  
  # Comando para hacer el build del proyecto
  command = "npm run build"
  
  # Directorio donde se genera el build (Vite usa 'dist' por defecto)
  publish = "dist"

[build.environment]
  # Versi칩n de Node.js para el build
  NODE_VERSION = "18"

# Configuraci칩n para Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimizaci칩n
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos est치ticos con cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para fuentes
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"